### ISSUE TITLE
App.css file isn't being included in the build process

### ISSUE THREAD

**Issue by Kn0tas** [Bjogert/FireBanReplit#3]
Problem Explanation

The problem you're encountering is that the App.css file isn't being included in the build process when you run npm run build, even though it works fine during development (npm run dev). This can result in a white page or unstyled content in the production build. This issue typically arises due to a misconfiguration in the build process, incorrect file paths, or problems with the CSS processing setup in your build tool.
Steps to Start Testing for Solutions

    Verify App.css File Path and Import:
        Ensure the import statement in your React component (e.g., FireBanChecker.jsx) correctly points to the App.css file.
        Double-check the file path and ensure there are no typos.

    Check Build Configuration:
        Review your vite.config.js file to ensure it is configured to process CSS files correctly.
        Make sure you have included the necessary plugins and options for CSS processing.

    Inspect the Output Directory:
        After running npm run build, manually check the dist directory to verify if App.css is present and properly referenced in index.html.
        Look for any CSS files in the dist/assets directory and check if they are linked correctly in the output HTML.

    Clean and Reinstall Dependencies:
        Sometimes, issues can arise from corrupted or outdated dependencies. Remove the node_modules and dist directories, and delete the package-lock.json file.
        Reinstall all dependencies and rebuild the project to ensure a clean setup.

    Check the Console and Build Logs:
        Look at the terminal output and build logs for any warnings or errors related to CSS processing.
        Pay attention to any messages indicating missing files or issues with the CSS syntax.

Example Workflow

    Verify File Path:
        Open src/components/FireBanChecker.jsx and ensure the import statement is correct:

        import '../App.css';

    Check vite.config.js:
        Ensure your vite.config.js includes the necessary configurations for CSS:

        import { defineConfig } from 'vite';
        import react from '@vitejs/plugin-react';

        export default defineConfig({
          plugins: [react()],
          css: {
            preprocessorOptions: {
              css: {
                // Ensure Vite processes CSS files correctly
              },
            },
          },
        });

    Run Build Command and Inspect Output:
        Run npm run build and check the dist directory:

        cd dist
        ls
        cat index.html

    Clean and Reinstall Dependencies:
        Run the following commands:

        rm -rf node_modules dist package-lock.json
        npm install
        npm run build

    Check for Errors and Warnings:
        Observe the output in the terminal for any indications of what might be causing the issue.

By following these steps methodically, you can identify and resolve the issue preventing App.css from being included in the production build.

**Comment by Kn0tas** [comment]
Ah! From what I can see the "import '../App.css';" has an extra "fnutt" after .css in the FireBanChecker.jsx file. Let me know if that solves your problem.

**Comment by Kn0tas** [comment]
Nope, that is not it. Sorry... Hmm...

**Comment by Bjogert** [comment]
The persistent build issue related to the missing App.css file during the Vite build process has been resolved. 
The following steps were taken:
Update vite.config.js: 
Ensured CSS imports are handled correctly.Revert Configuration: 
Removed postcss.config.js and reverted to previous setup.Correct Imports: 
Verified that App.css is correctly imported in App.jsx and index.jsx.Successful Build: Confirmed that the build completes successfully without errors.

But the page is still just s white screen. So something is still wrong. But now it builds without errors... 

So.. I'm happy.. but also sad... Sappy.. 🥲

**Comment by Kn0tas** [comment]
Alright, then I will close this issue.

**Comment by Kn0tas** [comment]
Issue closed.
