### ISSUE TITLE
Updating the readme file.

### ISSUE THREAD

**Issue by Kn0tas** [Bjogert/FireBanReplit#7]
I was thinking of removing the getting started paragraph and replaceing it with the startup sequence we discussed over the phone as a first commit. Something like:

#### Dependencies
Install npm, Vite, and Node.js for your operating system according to the instructions at:

[https://nodejs.org/en/download/package-manager](https://nodejs.org/en/download/package-manager)

#### How to Start the App  
Run the following command in the FireBanReplit repository:

```bash
npm run dev
```

When you see the following output:
```bash
VITE v5.3.1 ready in 497 ms

➜  Local:   http://localhost:5173/FireBanReplit/
➜  Network: use --host to expose
➜  Press 'H' + 'Enter' to show help
```
Ctrl-click or copy the local HTTP link to your browser and you will be directed to the FireBanreplit site.

Let me know what you think and tell me if you want to keep something that is currently under the 'Getting started' paragraph that we should keep.

**Comment by Bjogert** [comment]
Very good idea. I'll implement it!
