### ISSUE TITLE
Discuss setting up a docker environment for the project.

### ISSUE THREAD

**Issue by Kn0tas** [Bjogert/FireBanReplit#8]
Use a Docker environment for our project to streamline and standardize our development process. Docker offers several benefits that align with our needs, including:

### Consistency Across Environments:
 Docker containers ensure that everyone works in an identical environment, minimizing the "it works on my machine" problem.

### Efficiency in Onboarding:
 New team members can get started with development immediately without needing to configure their local setup.

### Isolation of Dependencies:
 By using Docker, we can isolate dependencies at the application level rather than installing them on individual developer machines. This not only keeps our workstations clean but also minimizes conflicts between different projects.

While setting up Docker will require some initial effort, the long-term benefits in terms of reduced troubleshooting and onboarding time, as well as the assurance that our development environments are consistent, will significantly outweigh the setup costs. I believe this investment will enhance our development efficiency and could prevent potential issues related to environment discrepancies as we scale.

**Comment by Kn0tas** [comment]
I need permission to push to a new branch.
"remote: Permission to Bjogert/FireBanReplit.git denied to Kn0tas."

I have started to look into using Docker containers a bit more. See branch dev/kn0tas soon for a starting example, as soon as i get access. It is not done, and I am not sure it will run correctly yet, so please wait before merging it into the main branch.

**Comment by Bjogert** [comment]
I invited you as a collaborator and ones you accept you will be able to push to new branches.

**Comment by Kn0tas** [comment]
Great! I have accepted. I will close this issue.
